feat(added django test case)
snok/django-swagger-tester pull request #117
Opened 2020-12-13 20:01 UTC by Goldziher

This PR adds a DRF TestCase that can be extended when using Django based testing.

2020-12-13 20:01 UTC, Goldziher commented
This is in a draft state because it still needs tests. I am also not sure about adding an `assertRequest` method as well.

2020-12-14 08:24 UTC, sondrelg commented
Cool! This is what I wanted to do when starting the project, but moved away from it because I didn't see an obvious way of getting the method and route in a reliable way. This looks promising however 👍 

If this works, do you think it would be possible to create a wrapper function to automatically apply testing to individual tests as well? This way you might be able to test a 200-response test and a 400-response test, but leave the rest alone?

2020-12-14 18:28 UTC, Goldziher commented
ok @sondrelg PR is finished.

2020-12-14 18:43 UTC, sondrelg requested changes
Please delete the `.DS_Store` file; otherwise I have no comments, just a suggested docstring change for consistency.

Also, if you didn't see it, see my question about wrapper functions!

Good work 🚀

2020-12-14 18:43 UTC, sondrelg commented on django_swagger_tester/testing.py
> +            raise self.failureException from e
```suggestion
class OpenAPITestCase(APITestCase):
    """
    Extends APITestCase with OpenAPI assertions.
    """

    def assertResponse(self, response: Response, **kwargs: Any) -> None:
        """
        Assert response matches the OpenAPI spec.
        """
        route = kwargs.pop('route', response.request['PATH_INFO'])
        method = kwargs.pop('method', response.request['REQUEST_METHOD'])
        try:
            validate_response(response=response, method=method, route=route, **kwargs)
        except (SwaggerDocumentationError, CaseError) as e:
            raise self.failureException from e
```

2020-12-14 18:43 UTC, sondrelg commented on django_swagger_tester/testing.py
> +            raise self.failureException from e
^ Just to keep styling consistent.

2020-12-14 19:06 UTC, Goldziher commented
Removed DS_Store, 

I didnt see your question. What is it?

> If this works, do you think it would be possible to create a wrapper function to automatically apply testing to individual tests as well? This way you might be able to test a 200-response test and a 400-response test, but leave the rest alone?

Well for django tests it shouldnt be a problem - its basically a decorator. You can also do this with the client. 

On the other hand - my opinion on testing best practices is that tests should not obfuscate implementation: In production code its good to keep stuff dry. In tests though, repetition is fine because a good test is readable and descriptive, and above all - easy to maintain by people other than the person(s) who wrote it. 

So adding this kind of wrapper (not very pythonic - more JS tbh) or a decorator is possible, but I would avoid doing this.

2020-12-15 13:52 UTC, sondrelg approved these changes
🎉

2020-12-15 13:53 UTC, merged